### ISSUE TITLE
Unclear how choose 'ngx-translate.lookup.resourcesPath'

### ISSUE THREAD

**Issue by vLutsevich** [apk27/ngx-translate-lookup#10]
I don't understand what can I type for relative path for  'ngx-translate.lookup.resourcesPath'?

structure of my project: 
Project folder( with package.json)/src/app/assets/i18n/en_US.json
(src, app - standart structure of angular project)

**Comment by alexpkent** [comment]
I haven't tested it with relative paths, all usages have been full path. I can provide this though.

**Comment by alexpkent** [comment]
I have published a new extension version 1.1.2 for this PR. Thanks

**Comment by vLutsevich** [comment]
Oh, cool! Thank you. Now it became clear.
