### ISSUE TITLE
Nested JSON keys wanted

### ISSUE THREAD

**Issue by egozavr** [apk27/ngx-translate-lookup#19]
Hi! Great extension! But we need a lookup over nested JSON translations. Will it be supported?

**Comment by alexpkent** [comment]
So your JSON has parent nodes with child string values and possibly further child nodes again?

What about nested arrays similar to [this](https://github.com/ngx-translate/core/issues/686#issuecomment-390518550)

**Comment by egozavr** [comment]
Here is the example:
```json
{
  "foo": {
    "bar": {
      "word1": "smth1-translated",
      "word2": "smth2-translated"
    }
  }
}
```
In template it used this way:
```html
<span tranlate="foo.bar.word1"></span>
<span tranlate="foo.bar.word2"></span>
```

**Comment by alexpkent** [comment]
OK, that shouldnt be too much work.

**Comment by alexpkent** [comment]
Published version 1.2.0 of the extension with this PR

**Comment by alexpkent** [comment]
Closing as no response on new version/feature.

**Comment by egozavr** [comment]
Oh! Great, thanks 👍
