### ISSUE TITLE
Feature Request: Multiple resourcesPath 

### ISSUE THREAD

**Issue by Chumachenkovlad** [apk27/ngx-translate-lookup#21]
It would be great to have ability to get translations from the few files.
resourcesPath -> resourcesPaths: string[]

For example:
lazy loading of translations for different modules
server-side translations

Let me know if the contribution is allowed

**Comment by alexpkent** [comment]
That sounds like it would be useful, if you want to feel free to submit a pull request or I can look to add it in the future

**Comment by Chumachenkovlad** [comment]
Please, review the [PR](https://github.com/apk27/ngx-translate-lookup/pull/22)

**Comment by alexpkent** [comment]
Merged and extension published. Thanks
