### ISSUE TITLE
default regex seems to be broken. why is it still partially working for me?

### ISSUE THREAD

**Issue by andre-ellrich-adup** [apk27/ngx-translate-lookup#24]
Awesome plugin idea!

currently
`{{\\s?'([A-Za-z0-9_\\.]+)'\\s?|\\s?translate_}}`

how it should be
`{{\\s?'([A-Za-z0-9_\\.]+)'\\s?\\|\\s?translate\s?}}`

question:

why is there `_` in the end of the regex? Why is the pipe not escaped. It has a special meaning in regex.

somehow the plugin is not working for me with other regexes. I can provide examples if needed.

**Comment by alexpkent** [comment]
@andre-ellrich-adup I haven't had any problems with the regex as they are, but equally switching to your regex above also works.

Do you have examples of values in html where it isnt working with that regex?
