### ISSUE TITLE
Output always opens

### ISSUE THREAD

**Issue by Eventyret** [apk27/ngx-translate-lookup#27]
It seems every time the plugin will initialise it will open the "output" pane.
This seems to be on any project 
![image](https://user-images.githubusercontent.com/977232/117937432-e433c480-b2fd-11eb-8a74-5ea9d52acafd.png)
This means it has to be closed every time, I do not see an option for it either?

**Comment by Eventyret** [comment]
Thanks for this @alexpkent  :) If there is any assistance needed let me know!

**Comment by alexpkent** [comment]
No problem, hope its useful 👍
