### ISSUE TITLE
False warning "Missing resource string: 'undefined'"

### ISSUE THREAD

**Issue by MarcoB1234** [apk27/ngx-translate-lookup#5]
There seem to be a bug when ngx-translate is used as pipe inside the interpolation syntax {{...}}: if the closing curly braces contain 1 space after the end of 'translate', a squiggle appears saying _Missing resource string: 'undefined'_, see screenshot below:

![image](https://user-images.githubusercontent.com/26527963/46377625-f999da00-c690-11e8-954d-dff110560c87.png)

NB: if 0, 2, or more blank spaces are present, no squiggles are shown.

**Comment by alexpkent** [comment]
Thanks, I have another PR #7 that addresses this issue and I have added unit tests for the regex checks

**Comment by alexpkent** [comment]
Merged PR #7 to address this. Thanks.
